defaults:
  - base_model

model_type: dofas
task: classification
dofa_size: dofa_small
image_resolution: 224
embed_dim: 384
pretrained_path: "DOFA-S_ViT_small_e100_10k.pth"
out_features: true
full_finetune: false
