defaults:
  - base_dataset

dataset_type: senbench_dfc2020
task: classification
dataset_name: senbench_dfc2020
num_classes: 10
num_channels: 2
data_path: /home/ge86wof2/sentinelbench/dfc2020_s1s2
modality: s1
band_names: ['VV', 'VH']
band_wavelengths: [50000000, 50000000]
band_bandwidths: [1e9, 1e9]
image_resolution: 256
multilabel: false
ignore_index: 255
language_embed: null
input_mode: spectral
kernel_size: 16
key: null # only valid for non-spectral variables